In [1]:
import numpy as np 



Helps us to work with numerical data  fro example lets say we want to use climate data like temperture ,rainfall,humidity in a region to determine if the region is well suited for growing.the apples a really simple apporach for doing this would be. formualte the reltionship as linear equation wiuld be like.
YEILD_OF_APPLES=W1*TEMPERATURE+W2*RAINFALL+W3*HUMIDITY
help(np.dot) hepls us to know about the function

In [2]:
#for example let us take the kashmir as an example
w1,w2,w3=0.3,0.2,0.3
kash_temp=73
kash_rainfall=67
kash_humidity=43
kash_yield_apples=kash_temp*w1+kash_rainfall*w2+kash_rainfall*w3


In [3]:
print("the expected yield of apples in kashmir region tons per hectare",kash_yield_apples)

the expected yield of apples in kashmir region tons per hectare 55.39999999999999


before starting the actual numpy why creating the hundreards of dataset when there are datasturcture in the world of programmmig


In [4]:
#field=[temp,rainfall,humidity]
kash=[78,67,43]
hubli=[89,45,48]
banglore=[45,45,96]
weights=[0.1,0.2,0.3]
def calcu(field,weights):
    result=0
    for x,w in zip(field,weights):
        result+=x*w
    return result
print(calcu(hubli,weights))
print("-----------------------")
print(calcu(banglore,weights))
print("------------------------")




32.3
-----------------------
42.3
------------------------


In [5]:
hubli=np.array([89,45,48])
weights=np.array([0.1,0.2,0.3])
type(hubli)

#with help of np.dot helps us do the code and functions easier to write and perform in the code 
#for example to take oout the reslut of hubli simple we can help of dot function
np.dot(hubli,weights)
(hubli*weights).sum()

np.float64(32.3)

In [6]:
#BENEFITS OF NUMPY EASE TO USE .DOT(),SUM() INTERNALLY IN C+ WHOLE NUMPY ASSBMLEM CODE MACHINE CODE INTERPERTER IS NOT INVOLVE MUCH FASTER 
arr1=list(range(10000000))
arr2=list(range(10000000,20000000))
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)


In [7]:
%%time
reuse=0
for x1,x2 in zip(arr1,arr2):
    reuse+=x1*x2
reuse


CPU times: total: 1.47 s
Wall time: 1.63 s


833333233333335000000

In [8]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 15.6 ms
Wall time: 12.8 ms


np.int64(3229750016405177280)

In [9]:
#multidimesional arrays starts from here !!!
climate_data=np.array([[73,67,63],[91,88,45],[102,103,105]])
climate_data.shape

(3, 3)

In [10]:
#experimenting with the numpy arrays
arr3=np.array([[[11,12,1],[123,143,143]],[[456,789,456],[78945,45631,4563]]])
arr3.shape
arr3.dtype

dtype('int64')

In [11]:
#numpy has less datatypes then that of python but good to use 
np.matmul(arr1_np,arr2_np)
#a character which defines the matrix multiplication in python is "@"
#kindly use them to prefect them
#now will work with 




np.int64(3229750016405177280)

In [12]:
climate=np.genfromtxt('climate_data.txt',delimiter=",",skip_header=1)
climate

array([[31.2,  0. , 45. ],
       [22.1, 45.2, 88. ],
       [19.8, 32. , 82. ],
       [34. , 56. , 38. ],
       [26.4,  5.1, 62. ],
       [25. , 18.3, 75. ],
       [29.8,  2. , 54. ],
       [21.5, 58.6, 92. ],
       [33.1,  0. , 41. ],
       [27.3,  8.2, 64. ],
       [23.9, 22.5, 79. ],
       [18.5, 15. , 73. ],
       [30.5,  0. , 49. ],
       [24.8, 38.1, 85. ],
       [28.1,  4.3, 59. ],
       [32.6,  0. , 43. ],
       [20.2, 64. , 95. ],
       [26.9, 11. , 70. ],
       [35.2,  0. , 33. ],
       [22.8, 27.4, 81. ],
       [29.1,  1.5, 52. ],
       [24.1, 19.8, 76. ],
       [17.9,  8.5, 66. ],
       [31.8,  0. , 46. ],
       [26. , 14.2, 71. ],
       [23.2, 41. , 87. ],
       [30. ,  0. , 50. ],
       [21. , 52.3, 90. ],
       [27.8,  6.7, 61. ],
       [33.5,  0. , 39. ],
       [25.4, 16.5, 74. ],
       [19.2, 29.1, 80. ],
       [28.9,  3.1, 56. ],
       [22.5, 35.8, 84. ],
       [34.6,  0. , 36. ],
       [26.2,  9.8, 67. ],
       [24. , 21. , 77. ],
 

In [13]:
climate.shape

(99, 3)

In [14]:
weights=np.array([0.3,0.2,0.5])
yields=climate@weights


In [15]:
yields

array([31.86, 59.67, 53.34, 40.4 , 39.94, 48.66, 36.34, 64.17, 30.43,
       41.83, 51.17, 45.05, 33.65, 57.56, 38.79, 31.28, 66.36, 45.27,
       27.06, 52.82, 35.03, 49.19, 40.07, 32.54, 46.14, 58.66, 34.  ,
       61.76, 40.18, 29.55, 47.92, 51.58, 37.29, 55.91, 28.38, 43.32,
       49.9 , 60.49, 31.6 , 39.59, 44.04, 32.77, 54.86, 42.62, 26.24,
       63.07, 47.65, 35.88, 49.77, 30.45, 41.09, 58.31, 36.1 , 28.64,
       52.35, 65.04, 45.45, 33.06, 41.56, 49.61, 29.69, 60.94, 38.14,
       54.64, 27.79, 44.31, 51.8 , 34.21, 51.07, 31.8 , 59.9 , 41.89,
       26.5 , 62.41, 46.86, 36.2 , 43.43, 30.34, 54.18, 42.84, 28.23,
       64.26, 40.16, 50.31, 32.21, 50.64, 44.18, 29.9 , 57.16, 48.19,
       35.83, 42.14, 30.92, 55.42, 42.99, 27.44, 61.04, 38.32, 49.71])

In [16]:
yields.shape

(99,)

SO WHATS BASICALLY HAPPENING HERE IS A MATRIX MULTIPLICATION THE USE CASES OF THE FUNCTIONS WILL BE EXPLAINED BELOW
1.)genfromtxt to know more about this run help(np.genfromtxt)
so now the calclution par looks for now 28.5,12.4,68*0.1,0.2,0.3 returns the value of the value is the matrix mul of the product


ARTHEMATIC OPERATIONS IN NUMPY 
element wise operation 
like scalar and adding to every element 
like remnder and else are show in one block of code 
NEXT BOXES CONTAIN THE ARTHEMATIC OPERATIONS ARE DOT,SUM,@

In [17]:
#the use of *
#dot product return if the array is like arr1-=[a,b,c] and arr2=[d,e,f]
#arr3=[a*d,b*e,c*f]
#that is the work of * in the numpy let us see with a working example
me=np.array([1,2,6])
me2=np.array([2,4,12])
me3=me*me2
print(me3)

[ 2  8 72]


In [18]:
#the use of dot in numpy
#now this works as 1*2+2*4+3*6=28 
#one of the usefull functions in nummpy sun and broadcasting are being skiped for now can include later
arr1=np.array([1,2,3])
arr2=np.array([2,4,6])
arr3=np.dot(arr1,arr2)
print(arr3)

28


SLICLING AND INDEXING EXAMPLES AND EXCISES SHOULD TAKE CARE OF AND SLICING DOES NOT PRISERVE THE ARRAY DIMENSIONS BUT THE RANGING INCLUDES THE PRISERVING THE ARRAY DIMENSIONS HAS INCLUDEAD IN THE CODE

In [19]:
#indexing 


arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

matrix = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200]
])
#Using indexing, print the element 50.
print(arr[4])
#Using negative indexing, print the element 90.
print(arr[-2])
#Using slicing, print the first 5 elements.
print(arr[0:5])
#Using slicing, print the elements from 60 to 90.
print(arr[5:9])
#Using slicing, print every second element starting from 20.
print(arr[1::2])
#Using slicing, print the array in reverse order.
print(arr[::-1])
#Using range(), print the elements at indices 0, 2, 4, 6, 8.
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

for i in range(0, 10, 2):
    print(arr[i])
#For the matrix, use 2D indexing to print 130.
print(matrix[2,2])
#For the matrix, use slicing to extract this section:
#70   80   90
#120  130  140
#170  180  190
print(matrix[1:,1:4])


50
90
[10 20 30 40 50]
[60 70 80 90]
[ 20  40  60  80 100]
[100  90  80  70  60  50  40  30  20  10]
10
30
50
70
90
130
[[ 70  80  90]
 [120 130 140]
 [170 180 190]]


 RESULT =50
90
[10 20 30 40 50]
[60 70 80 90]
[ 20  40  60  80 100]
[100  90  80  70  60  50  40  30  20  10]

10
30
50
70
90
130
[[ 70  80  90]
 [120 130 140]
 [170 180 190]]

OTHER WAYS OF CREATING NUMPY ARRAYS

In [20]:
#all zero array
print(np.zeros((3,2)))
#all ones
print(np.ones([2,2,3]))
#identity matrix
print(np.eye(3))
#random vector
print(np.random.rand(5))
#random matrix 
print(np.random.rand(2,3))
#fixed value
print(np.full([2,3],123))
#range with start,end and step
print(np.arange(0,126,2))
#shape of this 
print(np.arange(0,128,2).shape)
#reshaping 
print(np.arange(0,128,2).reshape(8,8))


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.58817532 0.49150831 0.48688353 0.49624876 0.73306076]
[[0.36747849 0.56273951 0.3452986 ]
 [0.17119432 0.03373637 0.03356943]]
[[123 123 123]
 [123 123 123]]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124]
(64,)
[[  0   2   4   6   8  10  12  14]
 [ 16  18  20  22  24  26  28  30]
 [ 32  34  36  38  40  42  44  46]
 [ 48  50  52  54  56  58  60  62]
 [ 64  66  68  70  72  74  76  78]
 [ 80  82  84  86  88  90  92  94]
 [ 96  98 100 102 104 106 108 110]
 [112 114 116 118 120 122 124 126]]


ANSWERS TO ABOVE CELL OR CODE
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.66432245 0.59595148 0.20310074 0.09242277 0.99157742]
[[0.9867964  0.30362258 0.14123938]
 [0.926427   0.6890356  0.16252674]]
[[123 123 123]
 [123 123 123]]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124]
(64,)
[[  0   2   4   6   8  10  12  14]
 [ 16  18  20  22  24  26  28  30]
 [ 32  34  36  38  40  42  44  46]
 [ 48  50  52  54  56  58  60  62]
 [ 64  66  68  70  72  74  76  78]
 [ 80  82  84  86  88  90  92  94]
 [ 96  98 100 102 104 106 108 110]
 [112 114 116 118 120 122 124 126]]

In [21]:
#wqually spaced numbers in a range 
np.linspace(3,30,10)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

THIS FILE CONTAINS BASICS OF MUPY TYOES OF THEM ,OPERATIONS AND BORADCASTING AND INDEXING AND SILCEING
-THANKYOU BY BALAJI BHAGIRATH BODDUCHERLA