In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
#convering into 2*3 array
print(arr.reshape(2,3))
print(arr.reshape(3,2))

arr1 = np.array([[10, 20], [30, 40], [50, 60]])
print(arr1.ravel())
#flatteing the array
print(arr1.flatten())



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
#convering into 2*3 array
print(arr.reshape(2,3))
print(arr.reshape(3,2))

arr1 = np.array([[10, 20], [30, 40], [50, 60]])
print(arr1.ravel())
#flatteing the array
print(arr1.flatten())

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[10 20 30 40 50 60]
[10 20 30 40 50 60]


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[10 20 30 40 50 60]
[10 20 30 40 50 60]

In [3]:
#Transpose — arr.T / np.transpose()

#Transpose swaps the axes of a 2-D matrix: rows become columns and columns become rows.
#Q1. Create a 2 × 4 matrix and find its transpose using .T. Print both shapes.
my_mat=np.array([[1,2,3,4],[5,6,7,8]])
print(my_mat.T)

#Q2. Verify that A.T and np.transpose(A) produce the same result.
print(np.transpose(my_mat))


[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

In [4]:
#matrix multiplication usinf @ and matmul
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(A@B)
#MATRIX MULTIPLICATION USING THE MATMUL FUNCTION
print(np.matmul(A,B))



[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]

In [5]:
#calculating the norm of the functions 
#v = np.array([3, 4])
#√(3² + 4²) = 5
#so now lets take a example if the norm 
v = np.array([1, 2, 2])
print(np.linalg.norm(v))
v1= np.array([3, 4])
normalized=v1/np.linalg.norm(v)
print(normalized)



3.0
[1.         1.33333333]


3.0
[1.         1.33333333]

In [6]:
#sloving the linear equations of the math into numpy
A = np.array([
    [2, 1],
    [1, 3]
])

b = np.array([5, 6])
x = np.linalg.solve(A, b)

print(x)
#example number two
"""x + 2y = 8
3x + y = 9"""
C=np.array([[1,2],[3,1]])
D=np.array([8,9])
res=np.linalg.solve(C,D)
print(res)


[1.8 1.4]
[2. 3.]


[1.8 1.4]
[2. 3.]

In [7]:
Ab = np.array([
    [2, 0],
    [0, 5]
])
eigenvalues, eigenvectors = np.linalg.eig(A)


print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[1.38196601 3.61803399]
Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


Eigenvalues:
[1.38196601 3.61803399]
Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]

In [8]:
ac=np.array([[45,5],[78,96]])
values,vectors=np.linalg.eig(ac)
print("eigenvectors")
print(vectors)
print("eigenvalues")
print(values)

eigenvectors
[[-0.59506207 -0.08625308]
 [ 0.80367975 -0.99627326]]
eigenvalues
[ 38.24709315 102.75290685]


SVD IS SINGULAR VALUE DECOMPOSTION IN LINEAR ALGEBRA IS A METHOS USED TO DECOMPOSTION THE MATRIX WHERE MOSTLY IN USED IN DIFFERENT CONTEXT DATASCIENCE AND MACHINE LEARNING ANDD VARIOUS OTHER FIELDS .
TO UNDERSTAND THIS FUNCTION IN NUMPY NEED TO WATCH SOME YOUTUBE TUTRIOLS WHICH USEFULL TO UNDERSTAND THE CONCEPTS THE OVERALL FORMULA IS A MATRIX B=U{V^T
{ REFERS TO SUMATION
-THANK YOU 

In [9]:
#svd demo and pratice questions
single= np.array([
    [3, 0],
    [0, 2]
])
"""Find U, S, and Vt.
Print their shapes.
Create Sigma using np.diag(S).
Reconstruct A using:"""
u,su,vt=np.linalg.svd(single)
print("THE LEFT SINGLUAR MATRIX:")
print(u)
print("THE SUMATION")
print(su)
print("THE TRANSPOSE OF RIGHT SINGLUAR MATRIX:")
print(vt)


THE LEFT SINGLUAR MATRIX:
[[1. 0.]
 [0. 1.]]
THE SUMATION
[3. 2.]
THE TRANSPOSE OF RIGHT SINGLUAR MATRIX:
[[1. 0.]
 [0. 1.]]


THE LEFT SINGLUAR MATRIX:
[[1. 0.]
 [0. 1.]]
THE SUMATION
[3. 2.]
THE TRANSPOSE OF RIGHT SINGLUAR MATRIX:
[[1. 0.]
 [0. 1.]]

In [10]:
#finding out the norms of the array by eulidean methos where norm=sqrt(x^2+y^2)
#gives out the norm of the vector example 
normarray=np.array([7,8,4])
resu=np.linalg.norm(normarray)
print(resu)

11.357816691600547


In [11]:
#finding out the norm,normalized vector and normlized vector norm
v = np.array([3, 4])
print("THE NORM OF VECTOR V",np.linalg.norm(v))
print("THE NORMALIZATION OF VECTOR V",v/np.linalg.norm(v))
print("THE NORM OD MORMALIZED VECTOR",np.linalg.norm(v/np.linalg.norm(v)))

THE NORM OF VECTOR V 5.0
THE NORMALIZATION OF VECTOR V [0.6 0.8]
THE NORM OD MORMALIZED VECTOR 1.0


THE NORM OF VECTOR V 5.0
THE NORMALIZATION OF VECTOR V [0.6 0.8]
THE NORM OD MORMALIZED VECTOR 1.0